language: java
install: ./install-dependencies.sh
script: mvn clean package
jdk:
  - openjdk11
os:
  - linux
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a9afd06ac035d4543d61
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always